[serve]
# INFO: The address to serve on LAN.
addresses = ["127.0.0.1"]
# INFO: The address to serve on WAN.
# INACTIVE: address = "0.0.0.0"
# INFO: The port to serve on.
port = 8000

[build]
minify = "on_release"

# INACTIVE: We don't need this right now, but just in case, I'm going to keep it
# [[hooks]]
# stage = "post_build"
# command = "sh"
# command_arguments = ["-c", """
# if [ $TRUNK_PROFILE = "release" ]; then
#   for f in $TRUNK_STAGING_DIR/*.wasm; do
#     [ -f $f ] || continue
#     echo "$f"
#     wasm-opt -Oz $f -o $f
#   done
# fi
# """]