name: Deploy

# TODO: Make builds & deploys not be triggered by .md, comments, etc
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Install trunk
        run: cargo install trunk
      - name: Build
        run: trunk build --release --dist dist
      - name: Check if dist directory exists
        run: ls -la dist
      - name: Install Binaryen
        run: sudo apt install binaryen -y
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
          command: deploy